version: '3.3'

services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
  energymonitoring:
    image: energy_monitoring_usecase
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGO_ADDRESS=mongo:27017
